### ISSUE TITLE
Deploying LAMP with Docker on Linode

### ISSUE THREAD

**Issue by WebDevJL** [fffaraz/dockerweb#1]
Hi,

I have 2 questions to start and your answer may result in several other questions: 
1. Using your repo, are the security bits configured (fail2ban, modsecurity, mysql security)?
2. Using your repo, can I isolate users from each other (distinct LAMP Stack)?

Thanks.

**Comment by fffaraz** [comment]
Hi,

1.
fail2ban: No,
modsecurity: No
mysql security: I'm using the official Mariadb docker image by default.

2. Yes, each website runs inside a separate docker container and has no access to other websites.
