### ISSUE TITLE
docweb proxy:run --debug local.hosting

### ISSUE THREAD

**Issue by Johntaa** [fffaraz/dockerweb#2]
trying to run this command but got this error : 
Unable to find image 'fffaraz/proxy:latest' locally
docker: Error response from daemon: pull access denied for fffaraz/proxy, repository does not exist or may require 'docker login'.
See 'docker run --help'.

**Comment by fffaraz** [comment]
You need to run `docweb build:all` to build the required images first.

**Comment by Johntaa** [comment]
Already did that , but got this output


Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libgd2-xpm-dev
E: Package 'libpng12-dev' has no installation candidate
The command '/bin/sh -c chown root:root /script_*.sh && chmod 540 /script_*.sh &         & sync && /script_init.sh' returned a non-zero code: 100
+ /opt/dockerweb/docweb build web/php7nginx
Sending build context to Docker daemon  27.65kB
Step 1/4 : FROM fffaraz/web/php7nginx/base:latest
pull access denied for fffaraz/web/php7nginx/base, repository does not exist or          may require 'docker login'
+ /opt/dockerweb/docweb build app/phpmyadmin
Sending build context to Docker daemon  12.29kB
Step 1/3 : FROM fffaraz/web/php7nginx:latest
pull access denied for fffaraz/web/php7nginx, repository does not exist or may r         equire 'docker login'
+ echo DONE
DONE
+ exit 0

**Comment by fffaraz** [comment]
It should be fixed. Could you please try again?

**Comment by Johntaa** [comment]
update-initramfs: deferring update (trigger activated)
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for systemd (237-3ubuntu10) ...
Processing triggers for initramfs-tools (0.130ubuntu3) ...
+ apt-get -yq install build-essential gcc g++ make zlib1g-dev libpcre3-dev libssl-dev libxslt1-dev libgd2-xpm-dev libperl-dev libbz2-dev libfreetype6-dev libjpeg-turbo8-dev libpng-dev libxml2-dev libcurl4-gnutls-dev
Reading package lists...
Building dependency tree...
Reading state information...
`E: Unable to locate package libgd2-xpm-dev`

**Comment by Johntaa** [comment]
I noticed that the build process keeps installing  anonymous image  no tag no name ,
`" I think it is the ubuntu image . repeated many times"`

**Comment by fffaraz** [comment]
Hi,
I guess it's fixed now.

**Comment by vujovicigor** [comment]
had similar issue with web/php7apache, 
fixed it by adding : libzip-dev in /opt/dockerweb/web/php7apache/script_init.sh
at line 8:
apt-get -yq install git nano **libzip-dev** zip unzip wget libfreetype6-dev libjpeg62-turbo-dev libpng-dev zip unzip

then build it:
docweb build web/php7apache

**Comment by Aoshee** [comment]
Hello,
I run command: docweb build:all but error:
`checking for libzip... not found
configure: error: Please reinstall the libzip distribution
The command '/bin/sh -c chown root:root /script_*.sh && chmod 540 /script_*.sh && sync && /script_init.sh' returned a non-zero code: 1
+ /opt/dockerweb/docweb build app/phpmyadmin
Sending build context to Docker daemon  12.29kB
Step 1/3 : FROM fffaraz/web/php7nginx:latest
pull access denied for fffaraz/web/php7nginx, repository does not exist or may require 'docker login'
+ echo DONE
DONE
+ exit 0
`

I already install libzip-dev. I run in Ubuntu 16.04 LTS.
